### ISSUE TITLE
lineString.relate(circle) incorrect 

### ISSUE THREAD

**Issue by yohanakh** [locationtech/spatial4j#128] opened 2015-12-27 14:28 UTC
As in #127 , LineString (JtsGeometry) relate method return wrong value when applying on Circle
The shapes are:
Circle(Point(1,1), 1)
LineString(Point(0,0), Point(2,0))

Apparently it checks for the vertices and not for the line itself.
I am using Spatial4J 5.0

```javascript
    @Test
    public void test() throws ParseException {
        SpatialContext ctx = JtsSpatialContext.GEO;
        JtsGeometry lineStringGeo = (JtsGeometry) ctx.readShapeFromWkt("LINESTRING (0.0 0.0, 2.0 0.0)");
        com.spatial4j.core.shape.Shape circleGeo = ctx.readShapeFromWkt("BUFFER (POINT (1.0 1.0), 1.0)");
        SpatialRelation rel = lineStringGeo.relate(circleGeo);
        System.out.println("relationship: " + rel); // relationship: DISJOINT
    }
```

**Comment by dsmiley** [comment] 2015-12-28 07:12
Closing as duplicate of #127

**Closed by dsmiley** 2015-12-28 07:12 UTC
Labels: bug, duplicate
